FROM node:18.12.1-alpine3.17 AS base
RUN apk update && \
	apk add --no-cache libc6-compat && \
	apk add openssl1.1-compat
RUN corepack enable && corepack prepare pnpm@9.9.0 --activate

FROM base AS builder

WORKDIR /app

COPY package*.json pnpm-lock.yaml .

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY . .

RUN npx prisma generate

RUN npx prisma migrate deploy

EXPOSE 3000

CMD [ "pnpm", "dev" ]
